DROP DATABASE IF EXISTS flomabek_db;

CREATE DATABASE flomabek_db;
USE flomabek_db;

CREATE TABLE CUSTOMER (
USERID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
EMAIL VARCHAR(50) NOT NULL,
PHONE_NUMBER INT(10) NOT NULL,
ADDRESS VARCHAR(80) NOT NULL,
USER_PASSWORD VARCHAR(256) NOT NULL
);

CREATE TABLE ORDERS (
ORDER_NUMBER INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
DATE_AND_TIME DATETIME NOT NULL,
ITEM VARCHAR(30) NOT NULL,
USERID INT NOT NULL,
FOREIGN KEY(USERID) REFERENCES CUSTOMER(USERID),
FOREIGN KEY(ITEM) REFERENCES TECH(SERIALNO)
);

CREATE TABLE TECH (
SERIALNO VARCHAR(30) NOT NULL PRIMARY KEY,
AVAILABLE BOOLEAN NOT NULL,
LABEL VARCHAR(20) NOT NULL,
COLOUR CHAR(50),
COST FLOAT(10) NOT NULL
);

CREATE TABLE PHONES (
DUALSIM BOOLEAN NOT NULL,
INTERNAL_STORAGE INT(5) NOT NULL,
SERIALNO VARCHAR(30) NOT NULL PRIMARY KEY,
FOREIGN KEY(SERIALNO) REFERENCES TECH(SERIALNO)
); 

CREATE TABLE LAPTOPS (
SCREEN_SIZE INT(2) NOT NULL,
INTERNALSTORAGE INT(5),
SERIALNO VARCHAR(30) NOT NULL PRIMARY KEY,
FOREIGN KEY(SERIALNO) REFERENCES TECH(SERIALNO)
);


